// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYw4UnqGA8kFTq2K5X8WoVcmQlgmnlLfI',
    appId: '1:301073631645:web:01f384a4b08075e6c6c774',
    messagingSenderId: '301073631645',
    projectId: 'marzo-joseph-2b',
    authDomain: 'marzo-joseph-2b.firebaseapp.com',
    storageBucket: 'marzo-joseph-2b.firebasestorage.app',
    measurementId: 'G-V97J8ZFNNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9tGwysSChpS2Dk6WqugtCY-aJEzniwQ',
    appId: '1:301073631645:android:a6493582c3f9b907c6c774',
    messagingSenderId: '301073631645',
    projectId: 'marzo-joseph-2b',
    storageBucket: 'marzo-joseph-2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAqQm2qsjFPLqBBlOEfVBnvqqI4jONoA',
    appId: '1:301073631645:ios:5e70297ed4a2e3b9c6c774',
    messagingSenderId: '301073631645',
    projectId: 'marzo-joseph-2b',
    storageBucket: 'marzo-joseph-2b.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2bAguilar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAqQm2qsjFPLqBBlOEfVBnvqqI4jONoA',
    appId: '1:301073631645:ios:5e70297ed4a2e3b9c6c774',
    messagingSenderId: '301073631645',
    projectId: 'marzo-joseph-2b',
    storageBucket: 'marzo-joseph-2b.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2bAguilar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYw4UnqGA8kFTq2K5X8WoVcmQlgmnlLfI',
    appId: '1:301073631645:web:ef6d37fd2c5dedaec6c774',
    messagingSenderId: '301073631645',
    projectId: 'marzo-joseph-2b',
    authDomain: 'marzo-joseph-2b.firebaseapp.com',
    storageBucket: 'marzo-joseph-2b.firebasestorage.app',
    measurementId: 'G-KNKTJ3CQ6T',
  );
}
